---
# tasks file for nginx

    - name: Install EPEL Repo
      yum:
        name=epel-release
        state=present
      when:
        ansible_os_family == "RedHat"

    - name: Install nginx
      package:
        state: latest
        name:
          - nginx
      notify:
        - start nginx

    - name: Copy nginx configuration for wordpress
      template: src=default.conf dest=/etc/nginx/conf.d/default.conf
      notify: restart nginx