---
# tasks file for nginx

    - name: Install EPEL Repo
      yum:
        name=epel-release
        state=present
      when:
        ansible_os_family == "RedHat"

    - name: Install nginx
      package:
        state: latest
        name:
          - nginx
      notify:
        - start nginx

    - name: Copy nginx configuration for wordpress rhel
      template: src=default_rhel.conf dest=/etc/nginx/conf.d/default.conf
      notify: restart nginx
      when: ansible_os_family == "RedHat"

    - name: Copy nginx configuration for wordpress debian
      template: src=default_debian.conf dest=/etc/nginx/conf.d/default.conf
      notify: restart nginx
      when: ansible_os_family == "Debian"
